_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
                - 61
            "4": 3.12.8
            "5": 0.19.9
            "8":
                - 2
                - 3
                - 5
            "12": 0.19.9
            "13": windows-amd64
data_weight:
    value: 5
epochs:
    value: 50001
lr_model:
    value: 0.05
lr_rho:
    value: 0.01
lr_vis:
    value: 1e-05
pde_weight:
    value: 1
rho_init:
    value: 100
use_checkpoint:
    value: false
vis_init:
    value: 0.005
