_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
                - 55
                - 61
            "4": 3.10.12
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
data_weight:
    value: 1
epochs:
    value: 50001
lr_model:
    value: 0.01
lr_rho:
    value: 0.01
lr_vis:
    value: 1e-05
pde_weight:
    value: 1
rho_init:
    value: 100
use_checkpoint:
    value: false
vis_init:
    value: 0.005
