_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
                - 55
                - 61
            "4": 3.10.12
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
checkpoint_path:
    value: weights/model_0614_4.pt
data_weight:
    value:
        - 3
        - 3
        - 1
lr_P:
    value: 0.001
lr_rho:
    value: 0.002
lr_u:
    value: 0.001
lr_vis:
    value: 2e-07
num_epochs:
    value: 50001
pde_weight:
    value:
        - 1
        - 1
        - 1
rho_init:
    value: 10
use_checkpoint:
    value: true
vis_init:
    value: 0.001
wandb_name:
    value: newmodel_pinn_5
