_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
                - 55
                - 61
            "4": 3.10.12
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
bc_weight:
    value: 10000
checkpoint_path:
    value: weights/model_0614_9.pt
data_weight:
    value:
        - 5
        - 5
        - 1
lr_P:
    value: 0.1
lr_rho:
    value: 0.1
lr_u:
    value: 0.01
lr_vis:
    value: 0.0001
num_epochs:
    value: 100001
pde_weight:
    value:
        - 10
        - 10
        - 10
rho_init:
    value: 100
use_checkpoint:
    value: false
vis_init:
    value: 0.01
wandb_name:
    value: nocircle_weightones
